* About
This is the supplementary code (in Python 3.6) for the paper Y. Malitsky and K. Mishchenko [[https://arxiv.org/pdf/1910.09529.pdf]["Adaptive Gradient Descent without Descent"]]


The implemented adaptive method is a reliable tool for minimizing differentiable functions. It is among the most general gradient-based algorithms and its fast performance is theoretically guaranteed. The method is merely 3 lines:
--------
#+html: <p align="center"><img src="img/alg.svg" /></p>
--------

* Usage
There are 4 experiments in total. The first three are provided in the form of a Jupyter notebook and for the neural networks we include a PyTorch implementation of the proposed optimizer.

- [[logistic_regression.ipynb][Logistic regression]]
- [[matrix_factorization.ipynb][Matrix factorization]]
- [[cubic_regularization.ipynb][Cubic regularization]]
- [[pytorch/optimizer.py][Neural networks]]

* Reference
If you find this code useful, please cite our paper:
#+BEGIN_SRC
@article{malitsky2019adaptive,
  title={Adaptive gradient descent without descent},
  author={Malitsky, Yura and Mishchenko, Konstantin},
  journal={arXiv preprint arXiv:1910.09529},
  year={2019}
}
#+END_SRC
